name: flutter_google_places_sdk
description: A Flutter plugin for google places sdk that uses the native libraries on each platform
version: 0.3.7
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_ios:
    path: packages/flutter_google_places_sdk_ios
  flutter_google_places_sdk_web:
    path: packages/flutter_google_places_sdk_web
  flutter_google_places_sdk_android:
    path: packages/flutter_google_places_sdk_android
  flutter_google_places_sdk_windows:
    path: packages/flutter_google_places_sdk_windows
  flutter_google_places_sdk_linux:
    path: packages/flutter_google_places_sdk_linux
  flutter_google_places_sdk_macos: 
    path: packages/flutter_google_places_sdk_macos
  flutter_google_places_sdk_platform_interface:
    path: packages/flutter_google_places_sdk_platform_interface

dependency_overrides:
  flutter_google_places_sdk_ios:
      path: packages/flutter_google_places_sdk_ios

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
