name: flutter_google_places_sdk
description: A Flutter plugin for google places sdk that uses the native libraries on each platform
version: 0.3.7
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface:
      path: ../flutter_google_places_sdk_platform_interface/
  flutter_google_places_sdk_ios: ^0.1.3
  flutter_google_places_sdk_web: ^0.1.6
  flutter_google_places_sdk_android: ^0.1.8
  flutter_google_places_sdk_windows: ^0.1.4
  flutter_google_places_sdk_linux: ^0.1.4
  flutter_google_places_sdk_macos: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
